// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 PRSN EX Inc.

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { toCanonicalBytes, type JsonValue } from './jcs';

// The cross-implementation anchor: the committed golden generated by the Rust
// chokepoint (crypto/examples/gen_jcs_golden.rs, serde_jcs lineage). This
// independent implementation (ECMAScript JSON.stringify primitives) must
// produce byte-identical canonical output for every case — the KeyCombine-KAT
// pattern applied to the canonicalization layer the F-DOWNGRADE(b) web
// verification path checks signatures over. crypto/tests/jcs.rs re-asserts
// the Rust side against the same file, so neither lineage can drift.

const text = (b: Uint8Array) => new TextDecoder().decode(b);

interface GoldenCase {
  name: string;
  input: JsonValue;
  canonical: string;
  canonical_sha256: string;
}

interface AsymmetryCase {
  name: string;
  input: JsonValue;
  rust_canonical: string;
}

const golden = JSON.parse(
  readFileSync(
    fileURLToPath(
      new URL('../../../../docs/design/test-vectors/golden/jcs-cross-impl.json', import.meta.url),
    ),
    'utf-8',
  ),
) as { cases: GoldenCase[]; asymmetry_cases: AsymmetryCase[] };

describe('jcs (RFC 8785, SigDrive domain)', () => {
  it('matches the committed Rust-lineage golden byte-for-byte, every case', async () => {
    // 8 named cases + the 64-case seeded differential corpus (escape-heavy
    // keys, control chars, safe-int edges) — one committed byte truth.
    expect(golden.cases.length).toBeGreaterThanOrEqual(72);
    for (const c of golden.cases) {
      expect(text(toCanonicalBytes(c.input)), `case '${c.name}'`).toBe(c.canonical);
      const digest = await crypto.subtle.digest(
        'SHA-256',
        new TextEncoder().encode(c.canonical) as BufferSource,
      );
      const hex = [...new Uint8Array(digest)].map((x) => x.toString(16).padStart(2, '0')).join('');
      expect(hex, `case '${c.name}' committed digest`).toBe(c.canonical_sha256);
    }
  });

  it('sorts keys and strips whitespace (RFC 8785 §3.2.3)', () => {
    expect(text(toCanonicalBytes({ b: [1, 2, 3], a: { d: 4, c: 3 } }))).toBe(
      '{"a":{"c":3,"d":4},"b":[1,2,3]}',
    );
  });

  it('uses the required short escapes and leaves / and UTF-8 raw', () => {
    expect(text(toCanonicalBytes({ s: '\b\t\n\f\r"\\/\u00e9' }))).toBe(
      '{"s":"\\b\\t\\n\\f\\r\\"\\\\/\u00e9"}',
    );
    // Other control characters take the \u00xx form (JSON.stringify semantics).
    expect(text(toCanonicalBytes({ s: '\u0000\u001f' }))).toBe('{"s":"\\u0000\\u001f"}');
  });

  it('rejects non-integer numbers (outside the SigDrive domain)', () => {
    expect(() => toCanonicalBytes({ x: 1.5 })).toThrow();
    expect(() => toCanonicalBytes({ x: Number.MAX_SAFE_INTEGER + 2 })).toThrow();
  });

  it('THROWS on every committed asymmetry case the Rust lineage formats (the pinned direction)', () => {
    // The deliberate divergence outside the shared domain, recorded as
    // intent: where full serde_jcs float-formats, this port fails CLOSED —
    // a signature over such bytes can never verify here, it refuses first.
    // crypto/tests/jcs.rs asserts the Rust half of each same-named pair.
    expect(golden.asymmetry_cases.length).toBeGreaterThanOrEqual(4);
    for (const c of golden.asymmetry_cases) {
      expect(() => toCanonicalBytes(c.input), `asymmetry case '${c.name}'`).toThrow();
    }
  });

  it('rejects out-of-domain object keys (non-ASCII OR escape-class chars)', () => {
    // The S112 corpus finding: the Rust lineage orders escaped-form keys
    // non-RFC, so BOTH chokepoints refuse keys outside the enforced domain —
    // symmetric fail-closed, asserted here and in crypto/tests/jcs.rs.
    expect(() => toCanonicalBytes({ clé: 1 })).toThrow();
    expect(() => toCanonicalBytes({ 'a\tb': 1 })).toThrow();
    expect(() => toCanonicalBytes({ 'a"b': 1 })).toThrow();
    expect(() => toCanonicalBytes({ 'a\\b': 1 })).toThrow();
    expect(() => toCanonicalBytes({ ok: { 'a\u001fb': 1 } })).toThrow();
    // The plain-ASCII range itself stays fully accepted.
    expect(() => toCanonicalBytes({ 'a zZ0_~/.-:!@`{|}': 1 })).not.toThrow();
  });
});
