// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 PRSN EX Inc.
import { describe, expect, it } from 'vitest';
import { UploadCancelledError, UploadController, type UploadProgress } from './drive';
import { UploadBatch, type UploadBatchState } from './upload-batch';
import type { UploadSlots } from './upload-slots';
// The compiled catalogue: gitignored, generated by `npm ci`'s prepare (compile:i18n).
import { m } from './paraglide/messages.js';

/**
 * F2 (2026-09-23) — the batch scheduler and its record, against a STUB upload.
 * The slot mechanics inside `uploadFile` are pinned in drive.test.ts; here the
 * subject is what the scheduler does around them: how many files it opens, what
 * cancel and a per-file pause do, and what the panel is told.
 */

function progress(over: Partial<UploadProgress> = {}): UploadProgress {
  return {
    completedParts: 0,
    totalParts: 1,
    sentBytes: 0,
    totalBytes: 10,
    retries: 0,
    paused: false,
    waitingForCapacitySeconds: null,
    inFlightParts: 0,
    measuredRateBytesPerSec: null,
    etaSeconds: null,
    suspensions: 0,
    ...over,
  };
}

/** A stub transfer: each file "learns" N at its initiate, holds a slot for its
 *  one part for `holdMs`, then lands. The test drives pauses and failures by
 *  name. */
function stubUpload(opts: {
  served: number;
  holdMs: number;
  paused?: Set<string>;
  failing?: Map<string, unknown>;
  initiated?: string[];
}) {
  return async (
    file: { name: string; size: number },
    name: string,
    onProgress: (p: UploadProgress) => void,
    controller: UploadController,
    slots: UploadSlots,
  ): Promise<unknown> => {
    await Promise.resolve(); // the initiate round trip
    opts.initiated?.push(name);
    slots.learn(opts.served);
    controller.active = { fileId: `file-${name}`, uploadId: `up-${name}` };
    const release = await slots.acquire();
    try {
      if (controller.cancelled) throw new UploadCancelledError();
      onProgress(progress({ inFlightParts: 1, totalBytes: file.size }));
      await new Promise((r) => setTimeout(r, opts.holdMs));
      if (opts.paused?.has(name)) {
        onProgress(progress({ inFlightParts: 0, totalBytes: file.size, paused: true }));
        const action = await controller.waitForResume();
        if (action === 'cancel') throw new UploadCancelledError();
        onProgress(progress({ inFlightParts: 1, totalBytes: file.size }));
        await new Promise((r) => setTimeout(r, opts.holdMs));
      }
      if (controller.cancelled) throw new UploadCancelledError();
      const failure = opts.failing?.get(name);
      if (failure !== undefined) throw failure;
      onProgress(
        progress({
          completedParts: 1,
          sentBytes: file.size,
          totalBytes: file.size,
          measuredRateBytesPerSec: 1000,
          etaSeconds: 0,
        }),
      );
      return { file_id: `file-${name}` };
    } finally {
      release();
      controller.active = null;
    }
  };
}

const files = (n: number, size = 10) =>
  Array.from({ length: n }, (_, i) => ({ name: `f${i}.jpg`, size }));

function harness(
  n: number,
  upload: ReturnType<typeof stubUpload>,
  over: Partial<ConstructorParameters<typeof UploadBatch>[0]> = {},
) {
  const states: UploadBatchState[] = [];
  const batch = new UploadBatch({
    files: files(n),
    dedupe: (d) => d,
    planParts: () => ({ chunkSize: 10, chunkCount: 1 }),
    upload,
    onState: (s) => states.push(s),
    initiallyVisible: true,
    now: () => 1_000,
    ...over,
  });
  return { batch, states };
}

describe('F2 — the batch scheduler (2026-09-23)', () => {
  it('opens ONE file until the pool learns N, then keeps N open — never more', async () => {
    const initiated: string[] = [];
    const { batch, states } = harness(8, stubUpload({ served: 4, holdMs: 10, initiated }));
    const outcome = await batch.run();
    expect(outcome).toEqual({ done: 8, cancelled: 0, failures: [] });
    expect(Math.max(...states.map((s) => s.filesOpen))).toBe(4);
    expect(Math.max(...states.map((s) => s.inFlightParts))).toBe(4);
    // Before the first initiate exactly one file is open; after it, four.
    const firstOpen = states.find((s) => s.filesOpen > 0)!;
    expect(firstOpen.filesOpen).toBe(1);
    expect(firstOpen.slots).toBe(0);
    expect(states.filter((s) => s.slots === 0).every((s) => s.filesOpen <= 1)).toBe(true);
    expect(states.some((s) => s.slots === 4 && s.filesOpen === 4)).toBe(true);
    // Files opened in order, named in order.
    expect(initiated).toEqual(files(8).map((f) => f.name));
    const last = states[states.length - 1];
    expect(last).toMatchObject({
      filesDone: 8,
      filesOpen: 0,
      completedParts: 8,
      totalParts: 8,
      sentBytes: 80,
      totalBytes: 80,
    });
  });

  it('the record sums what is open and forecasts what is pending; "files a–b of n" names the open range', async () => {
    const { batch, states } = harness(6, stubUpload({ served: 2, holdMs: 10 }));
    await batch.run();
    // A moment with two open: their indexes are consecutive and the range says so.
    const two = states.find((s) => s.filesOpen === 2 && s.inFlightParts === 2)!;
    expect(two).toBeDefined();
    expect(two.lastOpenIndex - two.firstOpenIndex).toBe(1);
    expect(two.fileName).toBe(`f${two.firstOpenIndex}.jpg`);
    expect(two.totalParts).toBe(6); // 2 open (reported) + 4 forecast, or later mixes — always the batch
    expect(two.totalBytes).toBe(60);
    // Sealing is true only before ANY file has reported.
    expect(states[0].sealing).toBe(true);
    expect(states.filter((s) => s.sealing).every((s) => s.completedParts === 0)).toBe(true);
    expect(states[states.length - 1].sealing).toBe(false);
    // The wall clock is the batch's, held in the record and never in the transfer facts.
    expect(states.every((s) => s.startedAt === 1_000)).toBe(true);
  });

  it('a paused file lists itself and does NOT stop the others; cancelling it rolls back only it (§2.7)', async () => {
    const paused = new Set(['f1.jpg']);
    const { batch, states } = harness(4, stubUpload({ served: 2, holdMs: 10, paused }));
    const run = batch.run();
    // Wait for the pause to be reported, with the batch still moving around it.
    const pausedState = await new Promise<UploadBatchState>((resolve) => {
      const tick = () => {
        const s = states.find((x) => x.pausedFiles.length > 0);
        if (s) resolve(s);
        else setTimeout(tick, 2);
      };
      tick();
    });
    expect(pausedState.pausedFiles).toEqual([{ fileIndex: 1, fileName: 'f1.jpg' }]);
    expect(pausedState.paused).toBe(false); // one of two open is paused: the batch is not
    // Let the rest finish around it.
    await new Promise((r) => setTimeout(r, 60));
    const around = states[states.length - 1];
    expect(around.filesDone).toBe(3);
    expect(around.paused).toBe(true); // now the ONLY open file is paused: the batch waits
    batch.cancelFile(1);
    const outcome = await run;
    expect(outcome).toEqual({ done: 3, cancelled: 1, failures: [] });
  });

  it('resuming the paused file completes it', async () => {
    const paused = new Set(['f0.jpg']);
    const { batch, states } = harness(1, stubUpload({ served: 2, holdMs: 5, paused }));
    const run = batch.run();
    await new Promise((r) => setTimeout(r, 30));
    expect(states[states.length - 1].paused).toBe(true);
    batch.resumeFile(0);
    expect(await run).toEqual({ done: 1, cancelled: 0, failures: [] });
  });

  it('batch cancel aborts every open file, opens nothing more, and keeps what landed (§2.6)', async () => {
    const { batch, states } = harness(8, stubUpload({ served: 4, holdMs: 20 }));
    const run = batch.run();
    await new Promise((r) => setTimeout(r, 30)); // the first four have landed, the next four are open
    expect(states[states.length - 1].filesDone).toBeGreaterThanOrEqual(1);
    batch.cancel();
    const outcome = await run;
    expect(outcome.failures).toEqual([]);
    expect(outcome.done + outcome.cancelled).toBe(8);
    expect(outcome.cancelled).toBeGreaterThanOrEqual(1);
    expect(batch.activeUploads()).toEqual([]);
  });

  it('a file failing on a definitive verdict is reported at batch end with the others landed — never silently', async () => {
    const boom = new Error('injected 4xx');
    const failing = new Map<string, unknown>([['f2.jpg', boom]]);
    const { batch, states } = harness(5, stubUpload({ served: 2, holdMs: 5, failing }));
    const outcome = await batch.run();
    expect(outcome.done).toBe(4);
    expect(outcome.failures).toEqual([{ fileIndex: 2, fileName: 'f2.jpg', error: boom }]);
    const last = states[states.length - 1];
    expect(last.filesFailed).toBe(1);
    // The failed file's bytes leave the totals, so the bar measures what was attempted.
    expect(last.totalBytes).toBe(40);
    expect(last.sentBytes).toBe(40);
  });

  it('F3-a: the batch ETA divides the remaining bytes by rate × parts in flight', async () => {
    // A stub that reports a measured rate WHILE its part is in flight, so a state
    // with four streams and a rate exists to check.
    const upload: ReturnType<typeof stubUpload> = async (
      file,
      name,
      onProgress,
      controller,
      slots,
    ) => {
      await Promise.resolve();
      slots.learn(4);
      const release = await slots.acquire();
      try {
        onProgress(
          progress({ inFlightParts: 1, totalBytes: file.size, measuredRateBytesPerSec: 2 }),
        );
        await new Promise((r) => setTimeout(r, 15));
        onProgress(
          progress({
            completedParts: 1,
            sentBytes: file.size,
            totalBytes: file.size,
            measuredRateBytesPerSec: 2,
            etaSeconds: 0,
          }),
        );
        return { file_id: name };
      } finally {
        release();
        controller.active = null;
      }
    };
    const { batch, states } = harness(8, upload);
    await batch.run();
    const four = states.find((s) => s.inFlightParts === 4 && s.measuredRateBytesPerSec !== null)!;
    expect(four).toBeDefined();
    // 80 bytes total, nothing sent yet, 2 B/s per stream × 4 streams = 10 s — not 40.
    expect(four.etaSeconds).toBe(Math.ceil((four.totalBytes - four.sentBytes) / (2 * 4)));
    expect(four.etaSeconds).toBe(10);
  });

  it('F3-c: files not yet opened are forecast at the CURRENT rate, so the total drops once and then holds', async () => {
    // The planner sizes parts from the governor's live rate: before any part has
    // been measured it plans the floor (5 parts per file here), after it the
    // measured size (1 part). A forecast frozen at batch start keeps 5 for every
    // file still pending, and the total then shrinks file by file as each
    // initiate replaces it — the v1.0.5 staging panel read 161 → 108 → 51.
    let part = 2; // the floor: a 10-byte file is 5 parts
    const upload: ReturnType<typeof stubUpload> = async (
      file,
      name,
      onProgress,
      controller,
      slots,
    ) => {
      await Promise.resolve();
      slots.learn(2);
      const release = await slots.acquire();
      try {
        part = 10; // the first part's measurement lands; every later plan is 1 part
        onProgress(progress({ totalParts: 1, inFlightParts: 1, totalBytes: file.size }));
        await new Promise((r) => setTimeout(r, 10));
        onProgress(
          progress({
            totalParts: 1,
            completedParts: 1,
            sentBytes: file.size,
            totalBytes: file.size,
          }),
        );
        return { file_id: name };
      } finally {
        release();
        controller.active = null;
      }
    };
    const { batch, states } = harness(6, upload, {
      planParts: (size) => ({ chunkSize: part, chunkCount: Math.ceil(size / part) }),
    });
    await batch.run();
    // Before the measurement: the floor's forecast for all six.
    expect(states[0].totalParts).toBe(30);
    // From the first report on, every file — open, done or pending — counts 1, so
    // the total is 6 and never moves again while files keep opening.
    const after = states.filter((s) => s.completedParts > 0 || s.inFlightParts > 0);
    expect(after.length).toBeGreaterThan(3);
    expect(after.some((s) => s.filesDone + s.filesOpen < s.fileCount)).toBe(true); // pending files existed
    expect(new Set(after.map((s) => s.totalParts))).toEqual(new Set([6]));
  });

  it('F3-c dead band: a rate wobbling across a part-count boundary holds the total; a real change moves it once', async () => {
    // Gus (review at c1f5fecb): a pending file's count is ceil(size / partSize) and
    // flips at every size / k; a 24-unit file sits across the 12 boundary when the
    // part size wobbles 11 ↔ 12.1. Following every wobble would move the total by
    // the pending count and back. Files open one at a time (N = 1); each sets the
    // planner's part size as it starts: the first measurement (floor 5 → 11), four
    // wobbles of a tenth, then the link halves (5.5).
    const schedule = [11, 12.1, 11, 12.1, 11, 5.5, 5.5, 5.5, 5.5, 5.5];
    let part = 5;
    let k = 0;
    const upload: ReturnType<typeof stubUpload> = async (
      file,
      name,
      onProgress,
      controller,
      slots,
    ) => {
      await Promise.resolve();
      slots.learn(1);
      const release = await slots.acquire();
      try {
        part = schedule[k++];
        onProgress(progress({ totalParts: 1, inFlightParts: 1, totalBytes: file.size }));
        await new Promise((r) => setTimeout(r, 2));
        onProgress(
          progress({
            totalParts: 1,
            completedParts: 1,
            sentBytes: file.size,
            totalBytes: file.size,
          }),
        );
        return { file_id: name };
      } finally {
        release();
        controller.active = null;
      }
    };
    const { batch, states } = harness(10, upload, {
      files: files(10, 24),
      planParts: (size) => ({ chunkSize: part, chunkCount: Math.ceil(size / part) }),
    });
    await batch.run();
    // Every finished file and every open file that has REPORTED counts 1 (the stub
    // reports 1), so at those moments the pending files' per-file forecast is what
    // is left of the total, over their number. (An open file not yet reported is
    // counted at its own forecast, so those instants are left out.)
    const perPending = states
      .filter((s) => s.inFlightParts === s.filesOpen)
      .map((s) => ({ s, pending: s.fileCount - s.filesDone - s.filesOpen - s.filesFailed }))
      .filter(({ pending }) => pending > 0)
      .map(({ s, pending }) => (s.totalParts - s.filesDone - s.filesOpen) / pending);
    // Consecutive duplicates collapsed: the floor's 5, the first measurement's 3 held
    // through all four wobbles (a live forecast would show 2 at 12.1), then the
    // halved link's 5 — once.
    const steps = perPending.filter((v, i) => i === 0 || v !== perPending[i - 1]);
    expect(steps).toEqual([5, 3, 5]);
  });

  it('one wake with parts in flight is ONE suspension for the batch, forwarded to every open file', async () => {
    const { batch, states } = harness(4, stubUpload({ served: 4, holdMs: 30 }));
    const run = batch.run();
    await new Promise((r) => setTimeout(r, 10)); // four in flight
    batch.setVisibility(false);
    batch.setVisibility(true);
    await run;
    expect(Math.max(...states.map((s) => s.suspensions))).toBe(1);
  });

  it('activeUploads lists the open files’ server ids for the pagehide abort', async () => {
    const { batch } = harness(3, stubUpload({ served: 4, holdMs: 30 }));
    const run = batch.run();
    await new Promise((r) => setTimeout(r, 10));
    expect(
      batch
        .activeUploads()
        .map((a) => a.uploadId)
        .sort(),
    ).toEqual(['up-f0.jpg', 'up-f1.jpg', 'up-f2.jpg']);
    await run;
    expect(batch.activeUploads()).toEqual([]);
  });
});

describe('F3-d — the batch line leads with the count (2026-09-23)', () => {
  it('says how many files are open beside the range, which files finishing out of order can make look larger', () => {
    // Four open, spread over 12–16 because file 13 already finished: the range
    // alone read as five at the v1.0.5 staging test.
    const line = m.filelist_uploading_batch({ open: 4, first: 12, last: 16, count: 30, pct: 45 });
    expect(line).toBe('Uploading 4 files (12–16 of 30) · 45%');
  });
});
