// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 PRSN EX Inc.

//! Human-side KEM-key wrap chain (Envelope §8 / WebAuthn-PRF v07): the committed
//! WebCrypto golden vector (Test Vector Category 01) + round-trip + the
//! failure-mode matrix (truncated PRF, wrong key, tamper, unknown alg).
//!
//! The golden at `docs/design/test-vectors/golden/kem-wrap.json` is generated by
//! `gen/kem_wrap_gen.mjs` (Node WebCrypto HKDF-SHA-256 + AES-256-GCM — the exact
//! chain the browser runs). Agreement proves our reference impl produces the same
//! bytes real sign-up/sign-in will, so the Phase-3 web client has a frozen oracle.

use base64::Engine;
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use serde_json::Value;
use signet_crypto::kem_wrap::{self, KemPrivkeyWrap};

const GOLDEN: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../docs/design/test-vectors/golden/kem-wrap.json"
));

fn vector() -> Value {
    let golden: Value = serde_json::from_str(GOLDEN).expect("parse committed kem-wrap golden");
    golden["kem_privkey_wrap"].clone()
}

fn hex_field(v: &Value, key: &str) -> Vec<u8> {
    hex::decode(v[key].as_str().unwrap()).expect("hex field")
}

fn fixed<const N: usize>(bytes: Vec<u8>) -> [u8; N] {
    bytes.try_into().expect("fixed-length field")
}

/// Cat 01 TC01-01: `prf_salt()` is `SHA-256("signet-drive-kem-wrap-v1")` — the
/// value the server sends as `prf.eval.first`. Pinned by NIST FIPS 180-4.
#[test]
fn prf_salt_matches_tc01_01() {
    assert_eq!(
        hex::encode(kem_wrap::prf_salt()),
        "e93d48bd9013c08e0bac7555f09312a3dd27c8e8a6d557fb325929d9a5cdf637",
    );
}

/// Cat 01 TC01-02: `derive_wrap_key(prf_output)` matches the WebCrypto golden `W`
/// (RustCrypto HKDF == WebCrypto HKDF for the §8.2 parameters).
#[test]
fn derive_wrap_key_matches_webcrypto_golden() {
    let v = vector();
    let w = kem_wrap::derive_wrap_key(&hex_field(&v, "prf_output_hex")).unwrap();
    assert_eq!(hex::encode(w), v["expected_w_hex"].as_str().unwrap());
}

/// §8.3: `wrap_kem_privkey(W, pkcs8, iv)` produces the WebCrypto golden `{ct,tag}`
/// (and the fixed `{v, alg, iv}` envelope shape).
#[test]
fn wrap_matches_webcrypto_golden() {
    let v = vector();
    let w: [u8; 32] = fixed(hex_field(&v, "expected_w_hex"));
    let pkcs8 = hex_field(&v, "pkcs8_hex");
    let iv: [u8; 12] = fixed(
        URL_SAFE_NO_PAD
            .decode(v["iv_b64u"].as_str().unwrap())
            .unwrap(),
    );

    let envelope = kem_wrap::wrap_kem_privkey(&w, &pkcs8, &iv).unwrap();
    assert_eq!(envelope.v, 1);
    assert_eq!(envelope.alg, "A256GCM");
    assert_eq!(envelope.iv, v["iv_b64u"].as_str().unwrap());
    assert_eq!(envelope.ct, v["expected_ct_b64u"].as_str().unwrap());
    assert_eq!(envelope.tag, v["expected_tag_b64u"].as_str().unwrap());
}

/// §8.5: unwrap recovers the exact PKCS#8 from the golden envelope.
#[test]
fn unwrap_recovers_webcrypto_golden_pkcs8() {
    let v = vector();
    let w: [u8; 32] = fixed(hex_field(&v, "expected_w_hex"));
    let envelope = KemPrivkeyWrap {
        v: 1,
        alg: "A256GCM".to_string(),
        iv: v["iv_b64u"].as_str().unwrap().to_string(),
        ct: v["expected_ct_b64u"].as_str().unwrap().to_string(),
        tag: v["expected_tag_b64u"].as_str().unwrap().to_string(),
    };
    let pkcs8 = kem_wrap::unwrap_kem_privkey(&w, &envelope).unwrap();
    assert_eq!(hex::encode(pkcs8), v["pkcs8_hex"].as_str().unwrap());
}

/// End-to-end round-trip from a PRF output: derive → wrap → unwrap.
#[test]
fn roundtrip_from_prf_output() {
    let w = kem_wrap::derive_wrap_key(&[7u8; 32]).unwrap();
    let pkcs8 = b"a stand-in PKCS#8 ECDH private key blob (arbitrary bytes)";
    let envelope = kem_wrap::wrap_kem_privkey(&w, pkcs8, &[0xABu8; 12]).unwrap();
    assert_eq!(kem_wrap::unwrap_kem_privkey(&w, &envelope).unwrap(), pkcs8);
}

/// A truncated / empty / oversized PRF output is rejected — never silently
/// truncated or padded (WebAuthn-PRF failure-modes table: full 32 bytes).
#[test]
fn non_32_byte_prf_output_rejected() {
    for len in [0usize, 16, 31, 33, 64] {
        assert!(
            kem_wrap::derive_wrap_key(&vec![0u8; len]).is_err(),
            "PRF output of {len} bytes must be rejected",
        );
    }
}

/// A different passkey's wrap key cannot unwrap — distinct PRF outputs derive
/// distinct `W` (the deterministic-PRF basis + "lose your passkey, lose data").
#[test]
fn wrong_wrap_key_fails() {
    let w_a = kem_wrap::derive_wrap_key(&[1u8; 32]).unwrap();
    let w_b = kem_wrap::derive_wrap_key(&[2u8; 32]).unwrap();
    assert_ne!(w_a, w_b);

    let envelope = kem_wrap::wrap_kem_privkey(&w_a, b"secret pkcs8 bytes", &[9u8; 12]).unwrap();
    assert!(kem_wrap::unwrap_kem_privkey(&w_b, &envelope).is_err());
}

/// Tampering with the ciphertext fails the GCM integrity check.
#[test]
fn tampered_ciphertext_fails() {
    let w = kem_wrap::derive_wrap_key(&[3u8; 32]).unwrap();
    let mut envelope = kem_wrap::wrap_kem_privkey(&w, b"secret pkcs8 bytes", &[4u8; 12]).unwrap();

    let mut ct = URL_SAFE_NO_PAD.decode(envelope.ct.as_bytes()).unwrap();
    ct[0] ^= 0x01;
    envelope.ct = URL_SAFE_NO_PAD.encode(&ct);

    assert!(kem_wrap::unwrap_kem_privkey(&w, &envelope).is_err());
}

/// An unrecognized `alg` is rejected before any AEAD work.
#[test]
fn unknown_alg_rejected() {
    let w = kem_wrap::derive_wrap_key(&[5u8; 32]).unwrap();
    let mut envelope = kem_wrap::wrap_kem_privkey(&w, b"x", &[6u8; 12]).unwrap();
    envelope.alg = "A128GCM".to_string();
    assert!(kem_wrap::unwrap_kem_privkey(&w, &envelope).is_err());
}
