// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 PRSN EX Inc.

//! Tests for the RFC 6962 / RFC 9162 Merkle tree (`signet_crypto::merkle`,
//! test-vector Cat 08/09/10).
//!
//! Two layers of assurance:
//!  - **Byte-exact KATs** (`*_matches_independent_vectors`, `*_is_exact`): the
//!    leaf/internal/root construction pinned against values computed by an
//!    independent implementation (Python `hashlib`) — the differential oracle for
//!    the domain separation (0x00 leaf / 0x01 internal) and the largest-power-of-2
//!    split. Leaves are `entry_hash` values (Option A); leaf `i` = the byte `i`
//!    repeated 32 times.
//!  - **Round-trip property tests** across many tree sizes: every inclusion proof
//!    and every consistency proof generated by this module verifies against the
//!    independently-computed `merkle_root`, and tampering (leaf / proof / root /
//!    range) is rejected. Generation follows RFC 6962 §2.1.1/§2.1.2; verification
//!    follows RFC 9162 §2.1.3.2/§2.1.4.2 — two distinct algorithms cross-checking
//!    each other through the `merkle_root` oracle.

use signet_crypto::merkle;

/// Lowercase hex of a hash (dependency-free, for comparing against pinned vectors).
fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// A KAT leaf: the byte `b` repeated 32 times (matches the Python oracle's
/// `bytes([b]) * 32`).
fn fill(b: u8) -> [u8; 32] {
    [b; 32]
}

/// A distinct property-test leaf keyed by `i` (big-endian in the first 8 bytes), so
/// trees of arbitrary size have all-distinct leaves without relying on SHA-256.
fn entry(i: usize) -> [u8; 32] {
    let mut e = [0u8; 32];
    e[..8].copy_from_slice(&(i as u64).to_be_bytes());
    e
}

#[test]
fn merkle_construction_matches_independent_vectors() {
    // Expected values computed independently with Python hashlib:
    //   leaf(e)        = sha256(b"\x00" + e)
    //   internal(l, r) = sha256(b"\x01" + l + r)
    //   root over leaves split at the largest power of two < n.
    let e: Vec<[u8; 32]> = (0u8..4).map(fill).collect();

    // Cat 10 TC10-01: the empty log hashes to SHA-256("").
    assert_eq!(
        hex(&merkle::merkle_root(&[])),
        "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    );

    // Cat 08: leaf hashes (0x00-prefixed).
    assert_eq!(
        hex(&merkle::leaf_hash(&e[0])),
        "7f9c9e31ac8256ca2f258583df262dbc7d6f68f2a03043d5c99a4ae5a7396ce9"
    );
    assert_eq!(
        hex(&merkle::leaf_hash(&e[1])),
        "dcffe786ded16d283c663846ad0c4ff26558fccde36ca9d30b2ea19eade9fc0e"
    );

    // Cat 09: an internal node (0x01-prefixed) over the first two leaves.
    assert_eq!(
        hex(&merkle::internal_hash(
            &merkle::leaf_hash(&e[0]),
            &merkle::leaf_hash(&e[1])
        )),
        "28fb81e496897e0ce886f08602392e9239b65c659041e5202163e58ad898f444"
    );

    // Cat 10: roots for log sizes 1..4.
    // n=1: the root IS the single leaf hash.
    assert_eq!(
        hex(&merkle::merkle_root(&e[..1])),
        "7f9c9e31ac8256ca2f258583df262dbc7d6f68f2a03043d5c99a4ae5a7396ce9"
    );
    // n=2: internal(leaf0, leaf1).
    assert_eq!(
        hex(&merkle::merkle_root(&e[..2])),
        "28fb81e496897e0ce886f08602392e9239b65c659041e5202163e58ad898f444"
    );
    // n=3 (non-power-of-2): internal(internal(leaf0, leaf1), leaf2) — the lonely
    // third leaf is promoted, NOT padded or duplicated.
    assert_eq!(
        hex(&merkle::merkle_root(&e[..3])),
        "ba8d94b7fbcecae7b81c4c80574fe24734a6917bf9c1ecd66ff3e0c34ead4620"
    );
    // n=4: internal(internal(leaf0, leaf1), internal(leaf2, leaf3)).
    assert_eq!(
        hex(&merkle::merkle_root(&e[..4])),
        "fdea52008cdae79fa8bf806261959e23f5e11681646a2fa2bc9b5e56b32030a2"
    );
}

#[test]
fn single_leaf_root_is_the_leaf_hash() {
    let e = fill(7);
    assert_eq!(
        merkle::merkle_root(std::slice::from_ref(&e)),
        merkle::leaf_hash(&e)
    );
}

#[test]
fn inclusion_proof_for_index_0_of_3_is_exact() {
    // PATH(0, D[3]) = [leaf_hash(e1), MTH({e2})=leaf_hash(e2)] — deepest sibling first.
    let e: Vec<[u8; 32]> = (0u8..3).map(fill).collect();
    let proof = merkle::inclusion_proof(&e, 0);
    assert_eq!(proof.len(), 2);
    assert_eq!(
        hex(&proof[0]),
        "dcffe786ded16d283c663846ad0c4ff26558fccde36ca9d30b2ea19eade9fc0e"
    );
    assert_eq!(
        hex(&proof[1]),
        "cba8c596120bdb69debbd923d92cba948bde7c7d06a465a1bb7d98d3116038fa"
    );
    let root = merkle::merkle_root(&e);
    assert!(merkle::verify_inclusion(&e[0], 0, 3, &proof, &root));
}

#[test]
fn inclusion_proofs_round_trip_and_reject_tampering() {
    for n in 1..=33usize {
        let leaves: Vec<[u8; 32]> = (0..n).map(entry).collect();
        let root = merkle::merkle_root(&leaves);
        for m in 0..n {
            let proof = merkle::inclusion_proof(&leaves, m);
            assert!(
                merkle::verify_inclusion(&leaves[m], m, n, &proof, &root),
                "valid inclusion proof must verify (n={n}, m={m})"
            );

            // A tampered leaf must fail.
            let mut bad_leaf = leaves[m];
            bad_leaf[0] ^= 0xff;
            assert!(
                !merkle::verify_inclusion(&bad_leaf, m, n, &proof, &root),
                "tampered leaf must fail (n={n}, m={m})"
            );

            // A wrong root must fail.
            let mut bad_root = root;
            bad_root[0] ^= 0xff;
            assert!(
                !merkle::verify_inclusion(&leaves[m], m, n, &proof, &bad_root),
                "wrong root must fail (n={n}, m={m})"
            );

            // A tampered proof element must fail.
            if !proof.is_empty() {
                let mut bad = proof.clone();
                bad[0][0] ^= 0xff;
                assert!(
                    !merkle::verify_inclusion(&leaves[m], m, n, &bad, &root),
                    "tampered proof must fail (n={n}, m={m})"
                );
            }
        }
    }
}

#[test]
fn consistency_proofs_round_trip_and_reject_tampering() {
    for n in 2..=33usize {
        let leaves: Vec<[u8; 32]> = (0..n).map(entry).collect();
        let new_root = merkle::merkle_root(&leaves);
        for m in 1..n {
            let old_root = merkle::merkle_root(&leaves[..m]);
            let proof = merkle::consistency_proof(&leaves, m);
            assert!(
                merkle::verify_consistency(m, n, &old_root, &new_root, &proof),
                "valid consistency proof must verify (m={m}, n={n})"
            );

            // A wrong old root must fail.
            let mut bad_old = old_root;
            bad_old[0] ^= 0xff;
            assert!(
                !merkle::verify_consistency(m, n, &bad_old, &new_root, &proof),
                "wrong old root must fail (m={m}, n={n})"
            );

            // A wrong new root must fail.
            let mut bad_new = new_root;
            bad_new[0] ^= 0xff;
            assert!(
                !merkle::verify_consistency(m, n, &old_root, &bad_new, &proof),
                "wrong new root must fail (m={m}, n={n})"
            );

            // A tampered proof element must fail.
            if !proof.is_empty() {
                let mut bad = proof.clone();
                bad[0][0] ^= 0xff;
                assert!(
                    !merkle::verify_consistency(m, n, &old_root, &new_root, &bad),
                    "tampered consistency proof must fail (m={m}, n={n})"
                );
            }
        }
    }
}

#[test]
fn proofs_reject_out_of_range_inputs() {
    let leaves: Vec<[u8; 32]> = (0..5).map(entry).collect();
    let root = merkle::merkle_root(&leaves);
    let any = merkle::leaf_hash(&leaves[0]);

    // index >= tree_size.
    assert!(!merkle::verify_inclusion(&leaves[0], 5, 5, &[], &root));

    // consistency with m >= n, or an empty proof, is rejected.
    assert!(!merkle::verify_consistency(5, 5, &root, &root, &[any]));
    assert!(!merkle::verify_consistency(6, 5, &root, &root, &[any]));
    assert!(!merkle::verify_consistency(2, 5, &root, &root, &[]));
}
